const characterLocations = {
    ruins: 'The Ruins',
    snowdin: 'Snowdin Forest',
    waterfall: 'Waterfall',
    hotland: 'Hotland',
    core: 'The Core',
    throneRoom: 'Throne Room',
    judgementHall: 'Judgement Hall',
    trueLab: 'The True Laboratory'
};

const characterData = [
    {location: characterLocations.ruins, name: 'Flowey', health: 6000, attack: 19, defense: 0, file: 'flowey.gif'},
    {location: characterLocations.ruins, name: 'Dummy', health: 15, attack: 0, defense: 0, file: 'dummy.png'},
    {location: characterLocations.ruins, name: 'Froggit', health: 30, attack: 5, defense: 4, file: 'froggit.gif'},
    {location: characterLocations.ruins, name: 'Loox', health: 50, attack: 6, defense: 6, file: 'loox.gif'},
    {location: characterLocations.ruins, name: 'Misgop', health: 40, attack: 7, defense: 5, file: 'misgop.gif'},
    {location: characterLocations.ruins, name: 'Migospel', health: 45, attack: 28, defense: 17, file: 'migospel.gif'},
    {location: characterLocations.ruins, name: 'Moldessa', health: 52, attack: 27, defense: 23, file: 'moldessa.gif'},
    {location: characterLocations.ruins, name: 'Moldsmal', health: 50, attack: 6, defense: 0, file: 'moldsmal.gif'},
    {location: characterLocations.ruins, name: 'Napstablook', health: 88, attack: 10, defense: 10, file: 'napstablook.gif'},
    {location: characterLocations.ruins, name: 'Parsnik', health: 72, attack: 30, defense: 28, file: 'parsnik.gif'},
    {location: characterLocations.ruins, name: 'Toriel', health: 440, attack: 80, defense: 80, file: 'toriel.png'},
    {location: characterLocations.ruins, name: 'Vegetoid', health: 75, attack: 6, defense: 6, file: 'vegetoid.gif'},
    {location: characterLocations.snowdin, name: 'Chilldrake', health: 74, attack: 12, defense: 7, file: 'chilldrake.gif'},
    {location: characterLocations.snowdin, name: 'Dogamy & Dogaressa', health: 198, attack: 14, defense: 5, file: 'ddg.gif'},
    {location: characterLocations.snowdin, name: 'Doggo', health: 70, attack: 13, defense: 7, file: 'doggo.gif'},
    {location: characterLocations.snowdin, name: 'Glyde', health: 220, attack: 9, defense: -20, file: 'glyde.gif'},
    {location: characterLocations.snowdin, name: 'Greater Dog', health: 105, attack: 15, defense: 8, file: 'greaterdog.png'},
    {location: characterLocations.snowdin, name: 'Gyftrot', health: 114, attack: 16, defense: 8, file: 'gyftrot.gif'},
    {location: characterLocations.snowdin, name: 'Ice Cap', health: 48, attack: 11, defense: 4, file: 'icecap.gif'},
    {location: characterLocations.snowdin, name: 'Jerry', health: 100, attack: 0, defense: 30, file: 'jerry.gif'},
    {location: characterLocations.snowdin, name: 'Lesser Dog', health: 60, attack: 23, defense: 3, file: 'lesserdog.gif'},
    {location: characterLocations.snowdin, name: 'Papyrus', health: 680, attack: 20, defense: 20, file: 'papyrus.png'},
    {location: characterLocations.waterfall, name: 'Aaron', health: 98, attack: 24, defense: 12, file: 'aaron.png'},
    {location: characterLocations.waterfall, name: 'Mad Dummy', health: 300, attack: 30, defense: 0, file: 'maddummy.gif'},
    {location: characterLocations.waterfall, name: 'Moldbygg', health: 70, attack: 18, defense: 18, file: 'moldbygg.gif'},
    {location: characterLocations.waterfall, name: 'Monster Kid', health: 100, attack: 2, defense: 2, file: 'monsterkid.png'},
    {location: characterLocations.waterfall, name: 'Shyren', health: 66, attack: 19, defense: 0, file: 'shyren.png'},
    {location: characterLocations.waterfall, name: 'Temmie', health: 5, attack: 7, defense: -20, file: 'temmie.gif'},
    {location: characterLocations.waterfall, name: 'Undyne', health: 1500, attack: 50, defense: 20, file: 'undyne.gif'},
    {location: characterLocations.waterfall, name: 'Undyne the Undying', health: 23000, attack: 99, defense: 99, file: 'undying.gif'},
    {location: characterLocations.waterfall, name: 'Woshua', health: 70, attack: 18, defense: 5, file: 'woshua.gif'},
    {location: characterLocations.hotland, name: 'Doodlebog', health: 100, attack: 8, defense: 999, file: 'doodlebog.gif'},
    {location: characterLocations.hotland, name: 'Mettaton EX', health: 1600, attack: 47, defense: 47, file: 'mettatonex.gif'},
    {location: characterLocations.hotland, name: 'Mettaton NEO', health: 30000, attack: 90, defense: 9, file: 'mettatonneo.gif'},
    {location: characterLocations.hotland, name: 'Mettaton (Normal)', health: 9999, attack: 30, defense: 255, file: 'mettaton.gif'},
    {location: characterLocations.hotland, name: 'Muffet', health: 1500, attack: 39, defense: 19, file: 'muffet.gif'},
    {location: characterLocations.hotland, name: 'Pyrope', health: 110, attack: 29, defense: 14, file: 'pyrope.gif'},
    {location: characterLocations.hotland, name: 'Royal Guards', health: 150, attack: 30, defense: 20, file: 'guards.png'},
    {location: characterLocations.hotland, name: 'So Sorry', health: 1100, attack: 9, defense: -6, file: 'sosorry.gif'},
    {location: characterLocations.hotland, name: 'Tsunderplane', health: 80, attack: 25, defense: 26, file: 'tsunderplane.gif'},
    {location: characterLocations.hotland, name: 'Vulkin', health: 20, attack: 25, defense: 0, file: 'vulkin.gif'},
    {location: characterLocations.core, name: 'Astigmatism', health: 120, attack: 32, defense: 26, file: 'astigmatism.gif'},
    {location: characterLocations.core, name: 'Final Froggit', health: 100, attack: 30, defense: 24, file: 'ffroggit.gif'},
    {location: characterLocations.core, name: 'Knight Knight', health: 230, attack: 36, defense: 36, file: 'knightknight.gif'},
    {location: characterLocations.core, name: 'Madjick', health: 190, attack: 29, defense: 24, file: 'madjick.gif'},
    {location: characterLocations.core, name: 'Astigmatism', health: 120, attack: 32, defense: 26, file: 'astigmatism.gif'},
    {location: characterLocations.core, name: 'Whimsalot', health: 95, attack: 34, defense: 12, file: 'whimsalot.gif'},
    {location: characterLocations.trueLab, name: 'Endogeny', health: 100, attack: 9, defense: 999, file: 'endogeny.gif'},
    {location: characterLocations.trueLab, name: 'Lemon Bread', health: 100, attack: 8, defense: 9999, file: 'lemonbread.gif'},
    {location: characterLocations.trueLab, name: 'Memoryhead', health: 100, attack: 9, defense: 999, file: 'memoryhead.gif'},
    {location: characterLocations.trueLab, name: 'Reaper Bird', health: 100, attack: 9, defense: 9999, file: 'reaperbird.gif'},
    {location: characterLocations.trueLab, name: `Snowdrake's Mother`, health: 100, attack: -12, defense: -4, file: 'snowdrakemom.gif'},
    {location: characterLocations.throneRoom, name: 'Asgore Dreemurr', health: 3500, attack: 80, defense: 80, file: 'asgore.gif'},
    {location: characterLocations.throneRoom, name: 'Asriel Dreemurr', health: 9999, attack: 9999, defense: 9999, file: 'asriel.gif'},
    {location: characterLocations.throneRoom, name: 'Photoshop Flowey', health: 6000, attack: 19, defense: 0, file: 'pflowey.png'},
    {location: characterLocations.judgementHall, name: 'Sans', health: 1, attack: 1, defense: 1, file: 'sans.gif'}
];

module.exports.findCharacter = (characterName) => {
    return characterData.find(character => character.name.includes(characterName));
}